//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CevrimiciIkiKisininOynadigiSosOyunu_1812901019
{
    using System;
    using System.Collections.Generic;
    
    public partial class galibiyet
    {
        public int Id { get; set; }
        public string x { get; set; }
        public string o { get; set; }
    }
}
