//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CevrimiciIkiKisininOynadigiSosOyunu_1812901019
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mustafakoca : DbContext
    {
        public mustafakoca()
            : base("name=mustafakoca")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<Table1> Table1 { get; set; }
        public virtual DbSet<Tablemesaj> Tablemesajs { get; set; }
        public virtual DbSet<game> games { get; set; }
        public virtual DbSet<galibiyet> galibiyets { get; set; }
    }
}
