//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CevrimiciIkiKisininOynadigiSosOyunu_1812901019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string kullaniciadi { get; set; }
        public string sifre { get; set; }
        public string sifretekrar { get; set; }
    }
}
