//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CevrimiciIkiKisininOynadigiSosOyunu_1812901019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablemesaj
    {
        public int Id { get; set; }
        public string gonderen { get; set; }
        public string alici { get; set; }
        public string baslik { get; set; }
        public string icerik { get; set; }
    }
}
